
import dynamic from "next/dynamic";

export const componentRegistry: Record<string, any> = {
    "action-search-bar": dynamic(() => import("@/components/lumenui/action-search-bar")),
    "ai-input-search": dynamic(() => import("@/components/lumenui/ai-input-search")),
    "ai-loading": dynamic(() => import("@/components/lumenui/ai-loading")),
    "ai-prompt": dynamic(() => import("@/components/lumenui/ai-prompt")),
    "ai-text-loading": dynamic(() => import("@/components/lumenui/ai-text-loading")),
    "ai-voice": dynamic(() => import("@/components/lumenui/ai-voice")),
    "apple-activity-card": dynamic(() => import("@/components/lumenui/activity-card")),
    "avatar-picker": dynamic(() => import("@/components/lumenui/avatar-picker")),
    "background-paths": dynamic(() => import("@/components/lumenui/background-paths")),
    "beams-background": dynamic(() => import("@/components/lumenui/beams-background")),
    "bento-grid": dynamic(() => import("@/components/lumenui/bento-grid")),
    "card-flip": dynamic(() => import("@/components/lumenui/card-flip")),
    "command-button": dynamic(() => import("@/components/lumenui/command-button")),
    "currency-transfer": dynamic(() => import("@/components/lumenui/currency-transfer")),
    "dynamic-text": dynamic(() => import("@/components/lumenui/dynamic-text")),
    "file-upload": dynamic(() => import("@/components/lumenui/file-upload")),
    "gradient-button": dynamic(() => import("@/components/lumenui/gradient-button")),
    "loader": dynamic(() => import("@/components/lumenui/loader")),
    "shimmer-text": dynamic(() => import("@/components/lumenui/shimmer-text")),
    "slide-text-button": dynamic(() => import("@/components/lumenui/slide-text-button")),
    "smooth-drawer": dynamic(() => import("@/components/lumenui/smooth-drawer")),
    "smooth-tab": dynamic(() => import("@/components/lumenui/smooth-tab")),
    "social-button": dynamic(() => import("@/components/lumenui/social-button")),
    "switch-button": dynamic(() => import("@/components/lumenui/switch-button")),
    "toolbar": dynamic(() => import("@/components/lumenui/toolbar")),
    "type-writer": dynamic(() => import("@/components/lumenui/type-writer")),
    "delete-button": dynamic(() => import("@/components/lumenui/delete-button")),
};
