
import dynamic from "next/dynamic";

export const componentRegistry: Record<string, any> = {
    "action-search-bar": dynamic(() => import("@/components/lumenui/action-search-bar")),
    "ai-input-search": dynamic(() => import("@/components/lumenui/ai-input-search")),
    "ai-loading": dynamic(() => import("@/components/lumenui/ai-loading")),
    "ai-prompt": dynamic(() => import("@/components/lumenui/ai-prompt")),
    "ai-text-loading": dynamic(() => import("@/components/lumenui/ai-text-loading")),
    "ai-voice": dynamic(() => import("@/components/lumenui/ai-voice")),
    "apple-activity-card": dynamic(() => import("@/components/lumenui/activity-card")),
    "attract-button": dynamic(() => import("@/components/lumenui/attract-button")),
    "avatar-picker": dynamic(() => import("@/components/lumenui/avatar-picker")),
    "background-paths": dynamic(() => import("@/components/lumenui/background-paths")),
    "beams-background": dynamic(() => import("@/components/lumenui/beams-background")),
    "bento-grid": dynamic(() => import("@/components/lumenui/bento-grid")),
    "card-flip": dynamic(() => import("@/components/lumenui/card-flip")),
    "card-stack": dynamic(() => import("@/components/lumenui/paymentflow-card-stack")),
    "carousel-cards": dynamic(() => import("@/components/lumenui/carousel-cards")),
    "command-button": dynamic(() => import("@/components/lumenui/command-button")),
    "currency-transfer": dynamic(() => import("@/components/lumenui/currency-transfer")),
    "dynamic-text": dynamic(() => import("@/components/lumenui/dynamic-text")),
    "file-upload": dynamic(() => import("@/components/lumenui/file-upload")),
    "glitch-text": dynamic(() => import("@/components/lumenui/glitch-text")),
    "gradient-button": dynamic(() => import("@/components/lumenui/gradient-button")),
    "hold-button": dynamic(() => import("@/components/lumenui/hold-button")),
    "liquid-glass-card": dynamic(() => import("@/components/lumenui/liquid-glass-card")),
    "loader": dynamic(() => import("@/components/lumenui/loader")),
    "matrix-text": dynamic(() => import("@/components/lumenui/matrix-text")),
    "mouse-effect-card": dynamic(() => import("@/components/lumenui/mouse-effect-card")),
    "particle-button": dynamic(() => import("@/components/lumenui/particle-button")),
    "profile-dropdown": dynamic(() => import("@/components/lumenui/profile-dropdown")),
    "scroll-text": dynamic(() => import("@/components/lumenui/scroll-text")),
    "shape-hero": dynamic(() => import("@/components/lumenui/shape-hero")),
    "shimmer-text": dynamic(() => import("@/components/lumenui/shimmer-text")),
    "sliced-text": dynamic(() => import("@/components/lumenui/sliced-text")),
    "slide-text-button": dynamic(() => import("@/components/lumenui/slide-text-button")),
    "smooth-drawer": dynamic(() => import("@/components/lumenui/smooth-drawer")),
    "smooth-tab": dynamic(() => import("@/components/lumenui/smooth-tab")),
    "social-button": dynamic(() => import("@/components/lumenui/social-button")),
    "switch-button": dynamic(() => import("@/components/lumenui/switch-button")),
    "swoosh-text": dynamic(() => import("@/components/lumenui/swoosh-text")),
    "team-selector": dynamic(() => import("@/components/lumenui/team-selector")),
    "toolbar": dynamic(() => import("@/components/lumenui/toolbar")),
    "tweet-card": dynamic(() => import("@/components/lumenui/tweet-card")),
    "type-writer": dynamic(() => import("@/components/lumenui/type-writer")),
    "v0-button": dynamic(() => import("@/components/lumenui/v0-button")),
};
